[package]
name = "data-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.6.0"
ferris-says = "0.3.1"
flate2 = "1.0.30"
serde = { version = "1.0.203", features = ["derive"] }
